server:
  port: 9999
spring:
  application:
    name: trip-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.cloud.nacos.config.namespace} #引用bootstrap.yml中的namespace
    gateway:
      discovery:
        locator:
          enabled: true #让gateway可以发现nacos中的微服务
      routes:
#        路由id，只要保证唯一即可
        - id: user_route
          # uri: 路由转发的路径，匹配到的请求最终转发到哪里去
          # lb == load balance == 负载均衡
          uri: lb://user-service
          # 断言： 匹配规则，按照设置的断言规则进行匹配，如果匹配成功，则将晶球转发到uri上
          predicates:
            # 路径匹配，前缀匹配方式，只要以 /users/ 开头的请求，都会被转发到 uri 上去
            - Path=/u/**
          #过滤器，执行真正的转发之前，要执行哪些过滤器
          fiiters:
            # StripPrefix:跳过前缀的过滤器，此处配置为 1 则表示在转发求前，自动将第一个前缀删除
            # 例如: 请求地址为 /product-serv/products/1，此时将前缀删除后，会变成 /products/1
            - StripPrefix=1